version: '3.7'

networks:
  webserver:
    name: webserver
    driver: bridge

services:
  brfim.local:
    hostname: brfim.local
    image: brfim:latest
    build:
      context: .
      network: host
    restart: always
    ports:
      - 80:8080
    environment:
      MONGO_TIMEOUT: 0
      MONGO_DATABASE: brfim
      MONGO_URI: mongodb://brfim:brfim@mongo:27017
      MONITOR_ADDR: ":6060"
    networks:
      - webserver

  mongo:
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /docker/brfim/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: brfim
      MONGO_INITDB_ROOT_PASSWORD: brfim
    networks:
      - webserver

  mongo-express:
    hostname: mongoexpress
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: brfim
      ME_CONFIG_MONGODB_ADMINPASSWORD: brfim
    networks:
      - webserver
