name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REPOSITORY: ghcr.io/insidegallery/brfim
  SERVICE: brfim

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push image
        run: |
               echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io --username insidegallery --password-stdin
               docker build . --tag ${{ env.REPOSITORY }}:${{ env.RELEASE_VERSION }}
               docker push ${{ env.REPOSITORY }}:${{ env.RELEASE_VERSION }}

  deploy:
    needs: push-store-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Update k8s manifests
        run: |
                git config --global user.email info@inside.gallery
                git config --global user.name "Automatic Deploy"
                git clone https://${{ secrets.GIT_TOKEN }}@github.com/InsideGallery/k8s.git
                cd k8s
                git remote set-url origin https://${{ secrets.GIT_TOKEN }}@github.com/InsideGallery/k8s.git
                chmod +x ./update_version.sh
                ./update_version.sh --no-commit ${{ env.RELEASE_VERSION }} ${{ env.SERVICE }}
                git add services/BrfIM/brfim/values.yaml
                git commit -m "Update ${{ env.SERVICE }} to version ${{ env.RELEASE_VERSION }}"
                git push
