name: Go

on:
  push:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.4

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: Install dependencies
        run: |
          go install github.com/boumenot/gocover-cobertura@latest
          go install github.com/vladopajic/go-test-coverage/v2@latest
      - name: Test with the Go CLI
        run: |
          GOMAXPROCS=$(nproc) go test -coverprofile=coverage.out -cover -race -tags="unit" -p $(nproc) -parallel=$(nproc) ./...
          go-test-coverage --config=./.testcoverage.yml
          gocover-cobertura < coverage.out > coverage.xml
      - name: Bench
        run: go test -bench=. -run="^$$" ./...
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          path: coverage.xml
